### ISSUE TITLE
Tools do not compile with g++14

### ISSUE THREAD

**Issue by ltjax** [KhronosGroup/KTX-Software#1101]
I'm getting these errors with the `Reporter`s

```
In file included from /home/ltjax/.conan2/p/b/ktx0e591fa15a9b9/b/src/tools/ktx/command.cpp:6:
/home/ltjax/.conan2/p/b/ktx0e591fa15a9b9/b/src/tools/ktx/command.h: In instantiation of ‘void ktx::Reporter::fatal_usage(Args&& ...) [with Args = {const char (&)[26], const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]’:
/home/ltjax/.conan2/p/b/ktx0e591fa15a9b9/b/src/tools/ktx/command.h:233:31:   required from here
/home/ltjax/.conan2/p/b/ktx0e591fa15a9b9/b/src/tools/ktx/command.h:122:19: error: ‘args#0’ is not a constant expression
  122 |         fmt::print(std::cerr, std::forward<Args>(args)...);
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

See also: https://github.com/conan-io/conan-center-index/pull/28400#issuecomment-3693432592

I think the first parameter needs to be explicitly spelled out as `fmt::format_string` for compile-time checking, as described by the {fmt} author here: https://stackoverflow.com/a/69596901/518626 - or compile time checks be disabled via fmt::runtime or vformat

**Comment by MarkCallow** [comment]
It is set here:

https://github.com/KhronosGroup/KTX-Software/blob/0eaebb015c29a8945c8df4a35f9bf2cb5c925a7f/tools/ktx/CMakeLists.txt#L82-L86

After a little research, it looks like `target_compile_features` sets a minimum required but if CMAKE_CXX_STANDARD sets something higher that will be used. Check if Conan is setting CMAKE_CXX_STANDARD. Perhaps I should use

```
set_property(TARGET ktxtools PROPERTY CXX_STANDARD 17)
```
 instead. This will not be overridden by CMAKE_CXX_STANDARD.

There seem to be a lot of differences between c++17 and c++20, such as the one you encountered, that can break compilation so allowing an override to happen is not a good idea.

**Comment by ltjax** [comment]
That makes sense, and also explains why my build worked with v4.3.2, because it still used the `CXX_STANDARD` way of setting the language version.

So I take it you're not open to porting the code to compile with C++23? I just did it out of curiosity for everything but the tests, and it at least compiles for both 23 and 17 now. And it actually found a bug where a parameter was missing in `command_create.cpp` line 2713 (I suppose `in.filename()`?).

I could put that up as a PR if you want.

**Comment by MarkCallow** [comment]
I am open to updating the code to compile with C++23 but I think we need to retain the ability to compile on C++20. Since you have it compiling on C++17 and C++23 it should be fine on C++20 too. We were hoping that with a port to C++20 we could dispense with the fmt{} library but I have just discovered that C++20 does not have all the fmt{} features, e.g. `fmt::print`. Perhaps C++23 does. When I wrote about changing to CXX_STANDARD it was because the code as is would not compile on a more recent version than c++17.

I am happy to review a PR based on your work and certainly want the bug fix. 

I have just updated the tests (unittest, texturetests, etc.) to C++20, because I wanted to use std::barrier, so they probably will compile on C++23 as well now. The update was in PR #1098.
