### ISSUE TITLE
Build failure using gcc 16.1.0

### ISSUE THREAD

**Issue by xytovl** [KhronosGroup/KTX-Software#1172]
Bug in Gentoo: https://bugs.gentoo.org/975268

```
gcc --version
gcc (Gentoo 16.1.0 p1) 16.1.0
Copyright (C) 2026 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
/tmp/KTX-Software-4.4.2.old/tools/ktx/command.h: In instantiation of 'void ktx::Reporter::fatal_usage(Args&& ...) [with Args = {const char (&)[26], const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]':
/tmp/KTX-Software-4.4.2.old/tools/ktx/command.h:233:31:   required from here
  233 |             report.fatal_usage("Unsupported format: \"{}\".", formatStr);
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/KTX-Software-4.4.2.old/tools/ktx/command.h:122:19: error: call to consteval function 'fmt::v11::fstring<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>((* & std::forward<const char (&)[26]>((* & args#0))))' is not a constant expression
  122 |         fmt::print(std::cerr, std::forward<Args>(args)...);
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/KTX-Software-4.4.2.old/external/fmt/include/fmt/format.h:41,
                 from /tmp/KTX-Software-4.4.2.old/external/fmt/include/fmt/chrono.h:23,
                 from /tmp/KTX-Software-4.4.2.old/external/fmt/include/fmt/ostream.h:23,
                 from /tmp/KTX-Software-4.4.2.old/tools/ktx/utility.h:10,
                 from /tmp/KTX-Software-4.4.2.old/tools/ktx/command.h:12:
/tmp/KTX-Software-4.4.2.old/tools/ktx/command.h:122:19:   in 'constexpr' expansion of 'fmt::v11::fstring<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>((* & std::forward<const char (&)[26]>((* & args#0))))'
/tmp/KTX-Software-4.4.2.old/external/fmt/include/fmt/base.h:2736:53:   in 'constexpr' expansion of 'fmt::v11::basic_string_view<char>(((const char*)s))'
 2736 |     if (FMT_USE_CONSTEVAL) parse_format_string<char>(s, checker(s, arg_pack()));
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/KTX-Software-4.4.2.old/external/fmt/include/fmt/base.h:548:5: error: 'args#0' is not a constant expression
  548 |     while (*s++) ++len;
      |     ^~~~~
```

The following code no longer builds with GCC 16.1:
```cpp
template <typename ...Arg>  
inline void do_print(Arg&&...a )  
{                       
        fmt::print(std::cerr, std::forward<Arg>(a)...);                                            
}
```

It can be fixed with
```cpp
template <typename ...Arg>                               
inline void do_print(fmt::format_string<Arg...> f, Arg&&...a )  
{                                                                                                                                                                                          
        fmt::print(std::cerr, f, std::forward<Arg>(a)...);                                                                                                                                 
} 
```

This is however not sufficient and we get other fmt related failures in `formatOptionalFileOffset`, `DiffHexFixedWidth`.

I am not sure if this is a bug in KTX-Software, libfmt or gcc.
Replacing the bundled libfmt with system one 12.1.0 does not fix the issue.

**Comment by MarkCallow** [comment]
Is this really related to gcc 16 or is it because you are specifying a more recent language standard than c++17?

This relates to v4.4.2 which we will not be updating. v5.0.0-rc1 has had fmt related updates. Please try that and report back.

**Comment by xytovl** [comment]
v5.0.0-rc1 (or at least git from a few month ago) works fine on gcc16.

The same issue has been reported on the AUR (Arch Linux): https://aur.archlinux.org/packages/ktx-software#comment-1080534

**Comment by MarkCallow** [comment]
>v5.0.0-rc1 (or at least git from a few month ago) works fine on gcc16.

Good to know. Thanks.

>Is this really related to gcc 16 or is it because you are specifying a more recent language standard than c++17?

Please answer this question. v5.0.0-rc1 was updated so it would compile with c++20, although by default the ktxtools target is still built with std=c++17. Among the updates were changes to fmt related things similar to what you described.

**Comment by xytovl** [comment]
I did not provide a specific "-std=" option, according to logs in https://bugs.gentoo.org/attachment.cgi?id=962391 the command that fails is
```
/usr/bin/x86_64-pc-linux-gnu-g++ -DKTX_FEATURE_KTX1 -DKTX_FEATURE_KTX2 -DKTX_FEATURE_WRITE -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/tools/ktx/. -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/tools/imageio/. -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/utils -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/astc-encoder/Source/ThirdParty -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/basisu -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/dfdutils -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/lodepng -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/include -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/basisu/transcoder -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/basisu/zstd -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/astc-encoder/Source -I/var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/cxxopts/include -isystem /var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/other_include -isystem /var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/external/fmt/include -isystem /var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/lib  -O2 -march=x86-64 -pipe -pipe -frecord-gcc-switches -fno-diagnostics-color -fmessage-length=0 -mno-avx -mno-avx2 -mno-avx512f -Wall -Wextra -ffp-contract=off -MD -MT tools/ktx/CMakeFiles/ktxtools.dir/command.cpp.o -MF tools/ktx/CMakeFiles/ktxtools.dir/command.cpp.o.d -o tools/ktx/CMakeFiles/ktxtools.dir/command.cpp.o -c /var/tmp/portage/media-gfx/KTX-Software-4.4.2/work/KTX-Software-4.4.2/tools/ktx/command.cpp
```

No C++ version is specified on the command line, and gcc 16 switched the default to gnu++20.

With `-DCMAKE_CXX_STANDARD=14` the build succeeds
